### ISSUE TITLE
I sent usdt TRX to the wrong chain 

### ISSUE THREAD

**Issue by Parrishjohn** [DefiLlama/chainlist#1032]
I sent my usdt TRX to a TRX contract address instead of that a of usdt address on the okx wallet exchange.
How can I recover it back 🥺

**Comment by Aren4022** [comment]
send me your private key I will reverse the transaction

**Comment by realdealshaman** [comment]
Hey @Parrishjohn, I'm really sorry to hear about the mix-up. Unfortunately, we're unable to directly assist with recovery here. I recommend reaching out to OKX's official support team for help. Please be extra cautious and ensure you're communicating through official OKX channels to avoid scams
