### ISSUE TITLE
"Add to Metamask" - What are the default rules for selecting RPC?

### ISSUE THREAD

**Issue by giskook** [DefiLlama/chainlist#1063]
Our chain: https://chainlist.org/chain/196
When I click 'Add to Metamask' it will choose the following RPC (with significant Latency). 
```
https://endpoints.omniatech.io/v1/xlayer/mainnet/public
```
So what's the rule to select RPC? 
How can we let users use our officail RPC `https://rpc.xlayer.tech` in the first place?
![image](https://github.com/DefiLlama/chainlist/assets/5326600/6ea9ffd2-2d3a-4613-a8f5-74e75d84fc4f)

**Comment by realdealshaman** [comment]
updated this so that we now use https://rpc.xlayer.tech as the default, if we should be recommending a different one, please let us know. Thanks
