### ISSUE TITLE
opBNB icon link broken

### ISSUE THREAD

**Issue by owen-reorg** [DefiLlama/chainlist#1119]
![CleanShot 2024-05-31 at 11 11 34@2x](https://github.com/DefiLlama/chainlist/assets/103096885/2fbfdc92-54dc-41d7-8d71-5c53f6d85a85)

https://icons.llamao.fi/icons/chains/rsz_op_bnb.jpg

The icon link appears to be broken. Could you please fix it?

**Comment by ksvnar** [comment]
Спасибо вам очень хорошо

**Comment by realdealshaman** [comment]
Hey @owen-reorg , it's now fixed, thanks for reporting it
