### ISSUE TITLE
Jooo

### ISSUE THREAD

**Issue by LalinZ1** [DefiLlama/chainlist#1154]
Mi dirección pública para recibir ETH 0x97406c39c45521a92af27Eb104eE684fCf8a9C89

Págame mediante Trust Wallet: https://link.trustwallet.com/send?coin=10000324&address=0x97406c39c45521a92af27Eb104eE684fCf8a9C89&amount=5.0![qr-zksync:0x97406c39c45521a92af27Eb104eE684fCf8a9C89?amount=5.png](https://github.com/DefiLlama/chainlist/assets/171946728/75ea0f36-8ca2-4fb5-9cc9-a668cbfd2d49)

****--

**Comment by omnifient** [comment]
jojo
