### ISSUE TITLE
Blockheight is not visible on chainlist

### ISSUE THREAD

**Issue by Himanityagi27** [DefiLlama/chainlist#1171]
Hello Team,

We have added three public endpoints to the Chain list and raised a PR, which has been merged by your team. All the endpoints are now available in the UI, but it is not displaying the block height.

Although it initially seemed that our endpoints were not working, we have confirmed that they are functioning correctly and showing the block height when using the curl command.

Please see the details of the protocols and endpoints below:

Etherlink mainnet:
chain id: 42793
public endpoint: https://etherlink-mainnet-pub-l5p9tu.zeeve.net/rpc

Bahamut ocean:
chainid: 4058
public endpoint: https://Bahamut-ocean-6h42j7.zeeve.net

Bahamut:
chain id: 5165
public endpoint: https://Bahamut-mainnet-2h93.zeeve.net

Could you Please look into this issue.
Thanks

**Comment by 0xngmi** [comment]
This is the issue with those RPCS: https://github.com/DefiLlama/chainlist/issues/1155#issuecomment-2189617107

**Comment by 0xngmi** [comment]
Closing because this issue is a duplicate

**Comment by Amarylla923** [comment]
Zamhamswifko, zamhamrobursksi, att, taters, RKA, BRKA,AR, Rea, KKA, TT, TITA, Lu, ++++++ JEdI, Irena, Gage, Mily, Mizza,  lp3, RPPTMGM, Aliq, A³s², AA, FA, FA,, FAL, COF, PZ³, PEZ³, RJ51, MC³, meme, RL, RL, SR AMR, SSL, Jake,  JoJoS. CATS, L$

**Comment by Amarylla923** [comment]
Affiliates, I forgot YEE, Dt5, and Quals, CanQ, QQQ, OZRQS, ALANNA, Aladdin, Humphrey, Bogart, Bosphefious, Coe. , HaP, Pap,
