### ISSUE TITLE
Change Blast chain id

### ISSUE THREAD

**Issue by andreivladbrg** [DefiLlama/chainlist#1202]
According to Blast's [docs](https://docs.blast.io/building/network-information#blast-mainnet), the Mainnet chain id is 81457 and not 238:

https://github.com/DefiLlama/chainlist/blob/b3b405537dee07356fadaf578b2d60a4a2e8533d/constants/chainIds.json#L93
<img width="300" alt="image" src="https://github.com/user-attachments/assets/5a7d406f-be2f-46ee-bfaf-7037b96a9fa1">

**Comment by realdealshaman** [comment]
@andreivladbrg that is a different chain, not the same BlastL2

**Comment by andreivladbrg** [comment]
got it, thanks

**Comment by smol-ninja** [comment]
@realdealshaman it would be useful to include [Blast logo](https://brandkit.blast.io/) in the [Blast-l2 card](https://chainlist.org/?search=blast). People who rely on Chainlist can, atleast, accurately differentiate it from other similar names.

I myself made an error in picking the correct chain ID for Blast L2 as I depend on Chainlist to quickly obtain network information.
