### ISSUE TITLE
Flare icon resolves differently on IPFS vs DefiLlama/Chainlist frontend

### ISSUE THREAD

**Issue by dineshpinto** [DefiLlama/chainlist#1218]
Flare: https://chainlist.org/chain/14

The icon is defined in [ethereum-lists/chains/_data/icons/flare.json](https://github.com/ethereum-lists/chains/blob/4c85bfdbb5f824afdebd078cc05a82c3067e762e/_data/icons/flare.json#L4)

 In IPFS this resolves to (notice pink color):
<img width="400" alt="Screenshot 2024-08-03 at 10 29 16" src="https://github.com/user-attachments/assets/73cced9d-3ba0-45b9-b21e-d25c80fc70e8">

However, on both [Chainlist](https://chainlist.org/chain/14) and [DefiLlama](https://defillama.com/chain/Flare) this resolves to (notice black color):

<img width="350" alt="Screenshot 2024-08-03 at 10 30 21" src="https://github.com/user-attachments/assets/82ba9948-7268-4021-b796-4a9f42705ae5">

<img width="350" alt="Screenshot 2024-08-03 at 10 37 50" src="https://github.com/user-attachments/assets/afda6e81-4d95-45ee-b5fd-92606a592871">

The pink color logo is the correct one. Would appreciate some help in resolving this. Thank you.

**Comment by realdealshaman** [comment]
Hey @dineshpinto I've updated the logo to the new pink one posted above. You can hard refresh your page(ctrl+F5) to see it

**Comment by dineshpinto** [comment]
Hey @realdealshaman, the icon now resolves correctly on Chainlist (pink color), but on DefiLlama it still shows the old version (tried hard refresh).

<img width="400" alt="Screenshot 2024-08-22 at 11 33 22" src="https://github.com/user-attachments/assets/19baba06-17ab-443a-b5c8-426f5baaca7e">
<img width="400" alt="Screenshot 2024-08-22 at 11 34 21" src="https://github.com/user-attachments/assets/aaaa1065-c953-4bbc-8413-62c208b07c7f">
