### ISSUE TITLE
Unable to see the icon of Lestnet on chainlist.org

### ISSUE THREAD

**Issue by foxtrotravi** [DefiLlama/chainlist#1237]
Hi, can you please look into why the Lestnet icon doesn't shows up on the website chainlist.org. I am attaching the screenshot below:
<img width="1500" alt="Screenshot 2024-08-26 at 3 06 56 PM" src="https://github.com/user-attachments/assets/9416362d-a431-4265-b689-aeaa41ea671b">

Please tell me if there is anything that needs to be done from my side. Thanks.

**Comment by realdealshaman** [comment]
Hi @foxtrotravi, this is working as expected. We only add icons for chains that have already been listed on DeFiLlama

**Comment by meanMonk** [comment]
Hi
@foxtrotravi raised the issue on https://github.com/DefiLlama/icons/issues with icons needs to be added or pr against! if recommended! 

please do your research before!
