### ISSUE TITLE
Unable to see Gravity Icon on chainlist

### ISSUE THREAD

**Issue by HaynarCool** [DefiLlama/chainlist#1260]
hey chainlist team !
The gravity icon doesn't show up on chainlist.org
![image](https://github.com/user-attachments/assets/18c97e12-1af2-4312-958a-7c55e1a6c6ae)
Logo is included into
https://github.com/ethereum-lists/chains/blob/master/_data/icons/gravity.json
We also have gravity on defiLlama
![image](https://github.com/user-attachments/assets/25e1f40e-9c41-44d6-a26e-fe9f12e9e3a4)
Could you please help on this?

**Comment by realdealshaman** [comment]
Hey @HaynarCool I've now added gravity to our chainId.json so that the logo will appear

**Comment by Annchchuks** [comment]
How
