### ISSUE TITLE
Update currency on Amoy testnet

### ISSUE THREAD

**Issue by jarnaez728** [DefiLlama/chainlist#1261]
Since some days ago the new currency of this blockchain is POL instead MATIC
https://chainlist.org/chain/80002

**Comment by realdealshaman** [comment]
@jarnaez728 Hey, you need to submit a pull request so that it is changed here: https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-80002.json

once it is fixed on ethereum-lists it will also update on chainlist.org

**Comment by jarnaez728** [comment]
Thanks. I did the pull request. I hope it is ok, it is the first I do :)
Cheers
Javier
