### ISSUE TITLE
Toggle for testnets not working 

### ISSUE THREAD

**Issue by SvenMeyer** [DefiLlama/chainlist#1279]
- I search for Ethereum
- get mainnets
- toogle [ ]  Test Networks
- nothing shows up (or shows up for ~2 sec and then disappears)

**Comment by realdealshaman** [comment]
you have to use the name of the testnet you want to find

**Comment by ardamcan** [comment]
0xDdFD2A10dfcdFdaAFf25C1c62EedbD7239180BB6
