### ISSUE TITLE
IOTA EVM - Wrong RPCs

### ISSUE THREAD

**Issue by 12123wwww** [DefiLlama/chainlist#1298]
Source:
https://github.com/DefiLlama/chainlist/blob/abca6300c3f12492e1c41ca7e163f4a819f1c2f4/constants/extraRpcs.js#L1255

Dropping the correct info here;
 

8822: {
    rpcs: [
      "https://json-rpc.evm.iotaledger.net",
      {
        url: "https://iota-mainnet-evm.public.blastapi.io",
        tracking: "limited",
        trackingDetails: privacyStatement.blastapi,
      },
    ],
  },
  1075: {
    rpcs: [
      "https://evm-toolkit-api.evm.testnet.iotaledger.net",
      {
        url: "https://iota-testnet-evm.public.blastapi.io",
        tracking: "limited",
        trackingDetails: privacyStatement.blastapi,
      },
    ],
  },
  
  
Additionally, IOTA EVM TESTNET (Chain ID 8822 (0x2276)) RPCs that should be removed, as they connect to main-net;
https://iota-mainnet-evm.public.blastapi.io
https://json-rpc.evm.iotaledger.net

**Comment by realdealshaman** [comment]
Hey @12123wwww thanks for raising this issue, I've updated the entries, the changes will show in the next couple of hours
