### ISSUE TITLE
bug wrong RPC for Chiado testnet

### ISSUE THREAD

**Issue by radeksvarz** [DefiLlama/chainlist#1339]
https://chainlist.org/chain/10200

-> https://1rpc.io/gnosis

That is for Gnosis mainnet (id 100)
![image](https://github.com/user-attachments/assets/bccf7e2e-bd43-45bf-83ab-65e1dfab8c53)

**Comment by realdealshaman** [comment]
Hey, thanks for bringing this to our attention, I've removed the incorrectly placed rpc
