### ISSUE TITLE
Is it ok to make an npm package of this?

### ISSUE THREAD

**Issue by actuallymentor** [DefiLlama/chainlist#1382]
Hello team!

Is it ok if I make an npm package that periodically auto-updates? The base premise is a simple:

```
import { get_rpcs } from chainlist-unofficial

const all_rpcs = get_rpcs()
const mainnet_rpcs = get_rpcs( [ 1 ] )
const mainnet_and_sepolia_rpcs = get_rpcs( [ 1, 421614 ] )
```

I'd write a github action that periodically imports your [extraRpcs](https://github.com/DefiLlama/chainlist/blob/main/constants/extraRpcs.js) and [chainIds](https://github.com/DefiLlama/chainlist/blob/main/constants/chainIds.json) and publishes to npm.

I'm just checking so I don't upset anyone :)

**Comment by 0xngmi** [comment]
Feel free to make an npm package!

**Comment by actuallymentor** [comment]
Thanks for the heads up @0xngmi! With the caveat that I haven't tested the auto-update in the CI yet, the package is live at [actuallymentor/chainlist-rpcs](https://github.com/actuallymentor/chainlist-rpcs).

Thanks for maintaining this excellent list!

**Comment by actuallymentor** [comment]
Little follow-up update: the package is live and auto-updates once daily 👌
