### ISSUE TITLE
Doge transaction failture on Coinbase wallet

### ISSUE THREAD

**Issue by dnice0123** [DefiLlama/chainlist#1389]
Hello,

I am trying to send DOGE from my coinbase wallet to an exchange however when processing it gives me a 'Send Error' Something went wrong. Can you please advise?

**Comment by Elsonbastey** [comment]
> Hello,
> 
> I am trying to send DOGE from my coinbase wallet to an exchange however when processing it gives me a 'Send Error' Something went wrong. Can you please advise?


Hello @dnice0123 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID DOG19338
Please see the link below to our dedicated support line:
[Coinbase Wallet DApps Support Ticket Requests.](https://thedappsupport.com)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by realdealshaman** [comment]
@dnice0123 sorry we don't offer this type of support. You can try reaching out to someone at coinbase
