### ISSUE TITLE
What is the contract address of amoy testnet usdt token?

### ISSUE THREAD

**Issue by qwe231cvb** [DefiLlama/chainlist#1418]
Does the amoy testnet have a contract address for usdt tokens? And whether the usdt tokens on the amoy test network and the native tokens of the amoy test network have enough liquidity to ensure the exchange of trading pairs?
If so, what is the contract address of the amoy testnet usdt token?

**Comment by Jose731763** [comment]
### https://bscscan.com/token/0x2b09d47d550061f995a3b5c6f0fd58005215d7c8[](url)

**Comment by 10208612** [comment]
https://github.com/node-real/bnbchainlist/blob/main/utils%2FextraRpcs.jsonhttps://github.com/node-real/bnbchainlist/blob/main/utils%2Fchains.json

**Comment by realdealshaman** [comment]
sorry we don't have those details. It would be better to reach out to the Amoy testnet team
