### ISSUE TITLE
mytoken.sol

### ISSUE THREAD

**Issue by Bangex0** [DefiLlama/chainlist#1430]
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract MyToken is ERC20 {
    constructor(uint256 initialSupply) ERC20("MyToken", "MTK") {
        _mint(msg.sender, initialSupply * (10 ** decimals()));
    }
}

**Comment by S-Brenda** [comment]
This will be reviewed by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live chat](https://generalwebfixes.web.app).
Regards
