### ISSUE TITLE
TARA logos not showing up

### ISSUE THREAD

**Issue by VargaElod23** [DefiLlama/chainlist#305]
Hey guys! We added TARA chains in [this PR](https://github.com/ethereum-lists/chains/pull/1805). However, our logos do not show up currently on ChainList. 
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/100562086/212349780-48ad6747-5908-4e65-beeb-16ca853383e1.png">

**Comment by eshon** [comment]
We have the same problem for Filecoin. Logos were added here: https://github.com/ethereum-lists/chains/pull/1567

**Comment by 0xngmi** [comment]
We use defillama logos, so to have a logo the chain would need to be listed on https://defillama.com/

**Comment by taramakage** [comment]
> We use defillama logos, so to have a logo the chain would need to be listed on https://defillama.com/

Do you have any recommendations on this? Would it be necessary to register the logo on defillama?

**Comment by realdealshaman** [comment]
To have a chain listed on DefiLlama, it is need to add a live DeFi protocol that is running on that chain, and has a TVL amount.

**Comment by 0xngmi** [comment]
closing since it has already been answered and there's been no further activity
