### ISSUE TITLE
Filecoin logos are not showing up

### ISSUE THREAD

**Issue by eshon** [DefiLlama/chainlist#310]
Similar to https://github.com/DefiLlama/chainlist/issues/305, the Filecoin logos are not showing up at all. Logos were added here: https://github.com/ethereum-lists/chains/pull/1567

**Comment by 0xngmi** [comment]
we had issues with their ipfs logos so we switched to using logos from defillama

**Comment by eshon** [comment]
Then where / how can we update the Filecoin logo @0xngmi?

https://defillama.com/chain/Filecoin seems to have the correct logo
