### ISSUE TITLE
Trying to add more public RPCs but chains are not included

### ISSUE THREAD

**Issue by Mummyhap** [DefiLlama/chainlist#312]
I am trying to add more public PRCs for some chians (e.g. Klaytn Baobab, Ethereum Sepolia). Those chains can be found on the site (e.g. https://chainlist.org/chain/11155111). But they are not in the file (https://github.com/DefiLlama/chainlist/blob/main/constants/chainIds.json and https://github.com/DefiLlama/chainlist/blob/main/constants/extraRpcs.js)

Do we need to add those chains by Pull Request first?

**Comment by 0xngmi** [comment]
yeah, you can add a new chain there with a pull request, and add all the rpc links that you want in that same pr
