### ISSUE TITLE
zkSync v2 button does nothing

### ISSUE THREAD

**Issue by luciash** [DefiLlama/chainlist#334]
When trying to add [zkSync v2](https://chainlist.org/chain/324) clicking "Add to Metamask" button does not work. Adding other networks works just fine.

(Brave [Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-bit)](https://brave.com/latest/))

**Comment by DevCon1100** [comment]
Access

**Comment by luciash** [comment]
> Access

wdym? What access?

**Comment by OrestTa** [comment]
MM fails because no RPC URL is provided

**Comment by ozenc26** [comment]
ozenc

**Comment by 0xngmi** [comment]
seems to be working fine now
