### ISSUE TITLE
Resolve score issue

### ISSUE THREAD

**Issue by perltk45** [DefiLlama/chainlist#344]
Unitedbloc WSS score looks fine. 
Unitedbloc RPC shows red X for score.  Yet our RPC is fast and working fine...

How can we resolve this? 
Also, is our privacy notice inadequate in some way? We'd like to resolve that as well.

Thank you. See attached screenshot.
<img width="1319" alt="Screenshot 2023-02-08 at 1 54 40 PM" src="https://user-images.githubusercontent.com/19353330/217660461-29ff6e91-08f3-4748-9072-8f754732f36d.png">

**Comment by Brightlystake** [comment]
@0xngmi would you be able to advice/direct on how we can overcome this. Apologies for the tag not sure how to proceed on this.

**Comment by 0xngmi** [comment]
Just checked and score looks right currently, back when you took the screenshot it might have been unreacheable

![image](https://user-images.githubusercontent.com/80541789/224435781-4bd2c63f-fd65-48a4-a637-f02236978310.png)

Regarding privacy policy, if you could implement a policy that purges IP data after X time we would change your privacy rating to limited.
