### ISSUE TITLE
BNB Testnet rpc url seems fishy

### ISSUE THREAD

**Issue by heypran** [DefiLlama/chainlist#347]

**Comment by Llama0x** [comment]
Which one?

**Comment by heypran** [comment]
Mainnet-
This is warning I see on metamask
```According to our records the submitted RPC URL value does not match a known provider for this chain ID.```

**Comment by 0xngmi** [comment]
that just means that they dont have that provider in their list, its not an issue

besides as a testnet rpc there's not much they could do maliciously (i guess at most just collect info on you)

**Comment by heypran** [comment]
Can we change it to official urls?

```
Testnet
Network Name: Smart Chain - Testnet

New RPC URL: https://data-seed-prebsc-1-s1.binance.org:8545/

ChainID: 97

Symbol: BNB

Block Explorer URL: https://testnet.bscscan.com
```
src: https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain

**Comment by DOTT-001** [comment]
> 
> This is warning I see on metamask
> ```According to our records the submitted RPC URL value does not match a known provider for this chain ID.```
> 

No, you need to go to Google and do research on how to match your RPC URL value on MetaMask.🙂
