### ISSUE TITLE
Can chainlist.org redeploy?

### ISSUE THREAD

**Issue by seonggwonyoon** [DefiLlama/chainlist#349]
Hello, we updated bifrost testnet info and added bifrost mainnet to [ethereum-lists/chains](https://github.com/ethereum-lists/chains) and were wondering if chainlist.org can be redeploy soon?

@0xngmi or @realdealshaman

ref: 
https://github.com/ethereum-lists/chains/pull/2253
https://github.com/ethereum-lists/chains/pull/2256
https://github.com/ethereum-lists/chains/pull/2252

**Comment by OrestTa** [comment]
More frequent redeploys would be appreciated indeed :)
