### ISSUE TITLE
 Does it need your team approval or else ?

### ISSUE THREAD

**Issue by Arca-Labs** [DefiLlama/chainlist#406]
### I don't know why the following problem occurs：
<img width="873" alt="截屏2023-03-20 16 46 56" src="https://user-images.githubusercontent.com/124778943/226293241-414b3c81-fbc9-43de-b776-68f015b3686a.png">

hey, guys !
Is it necessary to approve or something else, please help?
thank you

**Comment by 0xngmi** [comment]
no need for approval, that is just for site previews, which are not needed to get your pr merged
