### ISSUE TITLE
not indexing new chain

### ISSUE THREAD

**Issue by d1onys1us** [DefiLlama/chainlist#414]
hi i added a new chain Taiko to ethereum/chains, and it's showing up in some other indexers: chainlist.wtf, chainlist.network. but i'm not sure why it's not showing up on chainlist.org.

**Comment by 0xngmi** [comment]
probably just needs a rebuild, will trigger one with some commits

**Comment by realdealshaman** [comment]
If its a testnet, chain id 167004, the testnet toggle mush be checked before it is visible

**Comment by 0xngmi** [comment]
closing because it's been solved, just tested it again now and it's working without flaw

![image](https://github.com/DefiLlama/chainlist/assets/80541789/0ede7910-eef1-4adb-accd-237ad182506e)
