### ISSUE TITLE
Filecoin RPC added to extraRpcs.js file not working

### ISSUE THREAD

**Issue by eshon** [DefiLlama/chainlist#427]
https://github.com/DefiLlama/chainlist/blob/8bce1ae47b5beab683cabdc6bdaa99fe70cc69a8/constants/extraRpcs.js#L2118

`https://infura.sftproject.io/filecoin/rpc/v1` is not a functional RPC and should be removed.

**Comment by realdealshaman** [comment]
I removed it thanks
