### ISSUE TITLE
Carbon logo is not showing up

### ISSUE THREAD

**Issue by randy75828** [DefiLlama/chainlist#467]
Hi, have added Carbon EVM chain in this PR [https://github.com/ethereum-lists/chains/pull/2668](url). The carbon chain is also listed on defillama. Can the UI be shown the same logo as defilamma?

![image](https://user-images.githubusercontent.com/44086461/234198808-c3a0dc4a-a579-45ff-92f5-c17356b3f8b0.png)
![image](https://user-images.githubusercontent.com/44086461/234198946-d13cc91e-21e8-4ed0-a847-6f6a327d380e.png)

**Comment by JamesHinshelwood** [comment]
Hi @randy75828 , we had a similar issue for our EVM chain. I managed to fix it by adding an entry to `constants/chainIds.json` in #468. You could try the same - The only thing to make sure is that your logo is accessible at https://icons.llamao.fi/icons/chains/rsz_${chain.chainSlug}.jpg, where `${chain.chainSlug}` is the value you've added to `chainIds.json`.

https://github.com/DefiLlama/chainlist/blob/c06bbd38452b0f341b4605499d66817d96ecd981/pages/chain/%5Bchain%5D.js#L64

Hope this helps and sorry if its wrong - I only worked this out by reading the code and trial-and-error :smile:

**Comment by randy75828** [comment]
Thank you it worked! @JamesHinshelwood

**Comment by 0xngmi** [comment]
closing because it's been solved
