### ISSUE TITLE
Is it possible to replace RPC chainID 15

### ISSUE THREAD

**Issue by cqcwasd** [DefiLlama/chainlist#485]
My chain ID: 15 already exists, I see that it already exists in the file but the Diode is also 15 but it cannot be used, can I update and replace it

**Comment by Ehsan129** [comment]
> My chain ID: 15 already exists, I see that it already exists in the file but the Diode is also 15 but it cannot be used, can I update and replace it

**Comment by realdealshaman** [comment]
@cqcwasd  It's necessary to reach out on this repo for assistance with chainIDs: https://github.com/ethereum-lists/chains
