### ISSUE TITLE
MetaMask State logs -  v6.5.0 (1104)

### ISSUE THREAD

**Issue by alokeutpal** [DefiLlama/chainlist#496]
![97202360279435.txt](https://github.com/DefiLlama/chainlist/files/11469148/97202360279435.txt)

0x977733C440e8f0664b0F289a8B56D8010EE4BaE0

**Comment by 0292568684** [comment]
0xa8406dB12746Ae5FF940972C8C8942A475D7eC68

**Comment by Elijah554** [comment]
0xE0Ae9EcbFCF05d41e5e34F9b1b802a5DE6f24fF2
