### ISSUE TITLE
Chainlist.org spoofing dossed Linea rpc endpoints

### ISSUE THREAD

**Issue by croll83** [DefiLlama/chainlist#504]
Hey team, 

we had lots of issues on our public rpc endpoint. we counted consistent 6.8K requests per second on our endpoint coming from multiple sources, location and UAs. 

All of them had https://chainlist.org origin. Probably a ddos spoofing your domain? 

`{"remote_ip":"10.80.160.197","remote_port":"44008","proto":"HTTP/1.1","method":"GET","host":"rpc.goerli.linea.build","uri":"/","headers":{"X-Request-Id":["515b6038f956b820773dd2950b9c8644"],"X-Forwarded-For":["103.248.203.105"],"X-Forwarded-Proto":["https"],"Pragma":["no-cache"],"Cache-Control":["no-cache"],"Accept-Encoding":["gzip, deflate, br"],"X-Forwarded-Port":["443"],"X-Forwarded-Scheme":["https"],"X-Scheme":["https"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"],"Origin":["https://chainlist.org"],"Accept-Language":["en-US,en;q=0.9"],"Sec-Websocket-Version":["13"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"Upgrade":["websocket"],"Connection":["upgrade"],"X-Real-Ip":["103.248.203.105"],"X-Forwarded-Host":["rpc.goerli.linea.build"],"Sec-Websocket-Key":["/K0WvXBScp1+ZSG1T8Ufcg=="]}}`

We had to decide to block the domain, so the outcome is that your website is not able to retrieve the correct status information for our RPC. we hope this will stop soon, as we will migrate the endpoint on Infura in a couple of days and remove this block.

I just wanted to give you a heads-up.

Many thanks...

**Comment by 0xngmi** [comment]
yeah there's no way this much traffic could have been generated from our website, someone is spoofing the origin

**Comment by Freesoule25** [comment]
@croll83 @0xngmi
