### ISSUE TITLE
Pulsechain and Pulsechain Testnet V4 - Block explorer settings incorret

### ISSUE THREAD

**Issue by JexxaJ** [DefiLlama/chainlist#523]
Hey team, looks like the block explorer settings are not correct for these two networks.

Mainnet Explorer setting should be: https://scan.pulsechain.com/

Testnet Explorer setting should be: https://scan.v4.testnet.pulsechain.com/

Thanks

**Comment by realdealshaman** [comment]
Hi, @JexxaJ PRs to update the block explorer need to be submitted here: https://github.com/ethereum-lists/chains

**Comment by realdealshaman** [comment]
this was fixed
