### ISSUE TITLE
Remove "https://rpc.nextsmartchain.com" from Bitkub Chain (Chain ID: 96)

### ISSUE THREAD

**Issue by TimeKrit** [DefiLlama/chainlist#550]
This RPC "https://rpc.nextsmartchain.com" isn't correct for Add Bitkub Chain Network.
So please remove it from Bitkub Chain RPC https://chainlist.org/chain/96

**Comment by adese3131** [comment]
Good

**Comment by realdealshaman** [comment]
removed, thanks
