### ISSUE TITLE
Deprecated networks don't show as deprecated in UI

### ISSUE THREAD

**Issue by eshon** [DefiLlama/chainlist#551]
For example, 2 Filecoin testnets (Hyperspace and Wallaby) were marked as deprecated in https://github.com/ethereum-lists/chains/pull/2888 but are still showing up in the chainlist.org UI: https://chainlist.org/?search=filecoin&testnets=true

- The deprecated / discontinued testnets are shown before live, usable testnets
- There is nothing marking them as deprecated in the UI

**Comment by Ifechukwudaniel** [comment]
Please close this issue

**Comment by realdealshaman** [comment]
@eshon Hello ser  , thanks for pointing this out. This issue seems to be resolved now, please don't hesitate to let us know if there is any else 🙏

**Comment by eshon** [comment]
@realdealshaman - FYI - this issue is still a problem in the chainlist.org UI:

https://chainlist.org/?search=filecoin&testnets=true still shows the Hyperspace testnet which was deprecated many months ago.

Will chainlist.org update its UI to hide deprecated testnets? Otherwise I will file a new issue for this.

**Comment by Amarylla923** [comment]
https://github.com/Amarylla923/didactic-eureka

**Comment by 0xngmi** [comment]
Fixed in #858
