### ISSUE TITLE
living assets icon does not appear on chainlist website

### ISSUE THREAD

**Issue by zorjak** [DefiLlama/chainlist#556]
Hello,

I added this PR https://github.com/ethereum-lists/chains/pull/2970/files a couple of weeks ago, to add our network on chainlist website.

However, this website does not show our icon,
https://chainlist.org/chain/1440

On this one, it is displayed properly https://chainid.network/

I am not sure if is it related, but I also opened a PR here also https://github.com/DefiLlama/chainlist/pull/535. 

Thanks in advance for your answer,
Zoran

**Comment by zorjak** [comment]
Hello,

I'm sorry for bothering you, but is there any update regarding this? Is there something I can do to help to move this forward?

Thanks in advance for your help!!
Zoran

**Comment by realdealshaman** [comment]
Hi, @zorjak the logos only show up for chains that are already being tracked on Defillama

**Comment by zorjak** [comment]
Thank you for your response @realdealshaman .
