### ISSUE TITLE
Logos for Syscoin Testnet and Rollux Testnet&Mainnet

### ISSUE THREAD

**Issue by develCuy** [DefiLlama/chainlist#562]
How should I proceed for adding logos to the following?

https://chainlist.org/chain/570
https://chainlist.org/chain/5700
https://chainlist.org/chain/57000

**Comment by harinarayanprajapat** [comment]
Thanks 🙏👍

**Comment by realdealshaman** [comment]
@develCuy Hi, we only add the logos to the chains we are tracking on Defillama, so testnets don't have them

**Comment by develCuy** [comment]
Thanks for your help @realdealshaman!
