### ISSUE TITLE
Public endpoint is in the file but not on the chainlist

### ISSUE THREAD

**Issue by Mummyhap** [DefiLlama/chainlist#567]
My colleague submit PR #560 to add  BlockPI Public Arbitrum-Goerli  endpoint and it is already merged. The endpoint is in the file but there is no BlockPI Public Arbitrum-Goerli on https://chainlist.org/chain/421613.
See line 894-896 in https://github.com/DefiLlama/chainlist/blob/main/constants/extraRpcs.js

**Comment by harinarayanprajapat** [comment]
Thanks 🙏

**Comment by realdealshaman** [comment]
@Mummyhap , I see that it is showing now, can we close this issue?

**Comment by Ifechukwudaniel** [comment]
Please close this issue
