### ISSUE TITLE
Let's include native token contract addresses on search result cards

### ISSUE THREAD

**Issue by streamerd** [DefiLlama/chainlist#589]
Let's include (link) native token addresses in our network search results. It would totally earn devs the time on searching native tokens (eg. wrapped eth) addresses.

We can link the currency names to a relating page, _eg.to MATIC's token contract address on its main and/or testnets._

![](https://i.imgur.com/OM6Nrcz.png)

If there's a platform having verified list with this info, would be great to have a look at. So far couldn't find something streamlined this.

**Comment by Ifechukwudaniel** [comment]
This would be nice

**Comment by ali136613** [comment]
چه بگوئیم از کجا
