### ISSUE TITLE
Clarify if it is spelled Chainlist or ChainList

### ISSUE THREAD

**Issue by fulldecent** [DefiLlama/chainlist#593]
Please also see https://github.com/tahowallet/extension/pull/3547#pullrequestreview-1525313143

**Comment by RYZZA196** [comment]
Chainlist

**Comment by fulldecent** [comment]
In Taho Wallet we changed it to ChainList

https://github.com/tahowallet/extension/pull/3547/files#diff-ab00c11c38120d649412c7c32fe935e0bd26d039753d0fef5b058afa86784feeR656

**Comment by 0xngmi** [comment]
both are good tbh
