### ISSUE TITLE
chainlist avax rpc is not updated

### ISSUE THREAD

**Issue by ZANDevelop** [DefiLlama/chainlist#664]
hi, we have updated the avax rpc URL  in the pr  (https://github.com/DefiLlama/chainlist/pull/659)

but the chanlist page is not updated ?
![image](https://github.com/DefiLlama/chainlist/assets/133337518/46bf9113-9aaa-463a-b9ae-cc95b65db719)

**Comment by abbas8713** [comment]
.

**Comment by realdealshaman** [comment]
@ZANDevelop it's fixed, thanks
