### ISSUE TITLE
Does not work ' Add to Metamask'

### ISSUE THREAD

**Issue by Farid116** [DefiLlama/chainlist#713]
I passed all the checks, added all the necessary information, there are in the lists -
https://chainlist.org/?search=tectum&testnets=false

The 'Connect Wallet' button is working-calling and connecting to the Metamask is working

but!

The button ' Add to Metamask' does not work.
When you click on it in the Tectum window, nothing happens.

However, when clicking for example in the 'Catechin Chain Management' window
Metamask opens and offers to add a network...

Why does the ' Add to Metamask' button
not work in the Tectum window?

P.S. the same problem on
https://chainid.network/

**Comment by 0xngmi** [comment]
it's possible that the issue is that you already have a chain added to metamask with the same id

**Comment by Farid116** [comment]
> it's possible that the issue is that you already have a chain added to metamask with the same id

Unfortunately, there is no such network.
And it is not added....

**Comment by Emdd1983** [comment]
> it's possible that the issue is that you already have a chain added to metamask with the same id

**Comment by realdealshaman** [comment]
@Farid116 Tectum only has one rpc added and it is not working. That's why you are not able to connect to it

**Comment by Farid116** [comment]
> @Farid116 Tectum only has one rpc added and it is not working. That's why you are not able to connect to it

Work was carried out on the server.
Now the server is working, the problems remain:
1. Does not respond to the button 'Connect Wallet'.
2. There is no icon.

What else to check?

**Comment by nnnnnnsssss** [comment]
Hye

**Comment by Farid116** [comment]
> Hye

Hye?

**Comment by nnnnnnsssss** [comment]
Check☑ on

**Comment by Farid116** [comment]
> > @Farid116 Tectum only has one rpc added and it is not working. That's why you are not able to connect to it
> 
> Work was carried out on the server. Now the server is working, the problems remain:
> 
> 1. Does not respond to the button 'Connect Wallet'.
> 2. There is no icon.
> 
> What else to check?

The problems have remained ...
has no one ever encountered such a thing?

**Comment by Farid116** [comment]
> Check☑ on

Tell me, please, what does this mean, what needs to be done?

**Comment by nnnnnnsssss** [comment]
Recheck

**Comment by Farid116** [comment]
> Recheck

Everything is still the same:
1 Does not respond to the button 'Connect Wallet'.
2 There is no icon.

😒😒😒

**Comment by Farid116** [comment]
> > Recheck
> 
> Everything is still the same: 1 Does not respond to the button 'Connect Wallet'. 2 There is no icon.
> 
> 😒😒😒

Can anyone help or suggest how to solve the problems?

**Comment by Amarylla923** [comment]
I have the same problem

**Comment by Farid116** [comment]
> I have the same problem

Hi
Did you manage to solve these problems?

**Comment by Amarylla923** [comment]
No
