### ISSUE TITLE
Get icons displayed on chainlist.org

### ISSUE THREAD

**Issue by neutrinoks** [DefiLlama/chainlist#733]
Hello,

I recently added basic specifications for our two networks, we are currently running. The two networks (Agung with EVM ChainID 9990 and Krest with EVM ChainID 2241) are proper listed, but the icons are not getting displayed - what do I have to do, to get them displayed? Or is it some frontend-issue? I also contacted the developer of chainlist.wtf, there was the same issue - he fixed something, and now the icons are getting displayed there...

Regards, Michael

**Comment by realdealshaman** [comment]
Hi @neutrinoks we only display icons as a note of chains that have already been listed on DefiLlama, if your chain has a live project with tvl we would be happy to help get it listed , you can find more info here: https://docs.llama.fi/list-your-project/submit-a-project

**Comment by neutrinoks** [comment]
Hi @realdealshaman ah ok. So in general the chains with EVM ChainID will be listed, but addition with icon only, if they are also listed on DeFiLama? So far we only support the basic EVM ChainID with RPC, but we have no TVL so far...

**Comment by realdealshaman** [comment]
Correct, we only need to list at least one project with tvl to get your chain logo added

we have more info on how to list a projects here: https://docs.llama.fi/list-your-project/submit-a-project

**Comment by neutrinoks** [comment]
Thanks :+1:
