### ISSUE TITLE
> Hey, send me THB 200,000.00 via Skrill using this link: https://skrill.me/rq/Tanancha/200000/THB?key=pBJhx-qSiJQUil24-46JyLiyIww

### ISSUE THREAD

**Issue by tanan499** [DefiLlama/chainlist#794]
> Hey, send me THB 200,000.00 via Skrill using this link: https://skrill.me/rq/Tanancha/200000/THB?key=pBJhx-qSiJQUil24-46JyLiyIww

Bank account 

_Originally posted by @tanan499 in https://github.com/tanan499/ccc.zx281-gmail.com/issues/8#issuecomment-1793615060_

**Comment by maristonimoura** [comment]
✍️

**Comment by Amarylla923** [comment]
Send me 20000000

**Comment by tanan499** [comment]
![Uploading Screenshot_2023-11-20-01-58-14-18_c37d74246d9c81aa0bb824b57eaf7062.jpg…]()

**Comment by tanan499** [comment]
My withdrawal
