### ISSUE TITLE
BSC Chain Scam website

### ISSUE THREAD

**Issue by lonelyIslanders** [DefiLlama/chainlist#797]
Since chrome marked bsc-dataseed5.digart.store as a scam website, the RPC node of the bsc chain will be intercepted by chrome and the chainlist will be marked as dangerous.

**Comment by realdealshaman** [comment]
@lonelyIslanders thank you for pointing this out, we've removed the rpc. Thanks again

**Comment by 0xngmi** [comment]
closing since it's been solved
