### ISSUE TITLE
why /api/chain/1 not available

### ISSUE THREAD

**Issue by jiangbo0216** [DefiLlama/chainlist#817]
there is a api/chain/[chain] in source code, here is the pr: https://github.com/DefiLlama/chainlist/pull/328

I try https://chainlist.org/api/chain/1, server response is `nope`

**Comment by nnnnnnsssss** [comment]
Marge

**Comment by sanmay321** [comment]
> there is a api/chain/[chain] in source code, here is the pr: #328
> 
> I try https://chainlist.org/api/chain/1, server response is `nope`

i think you have to use https://chainid.network/chain/eth this

**Comment by aniketfuryrocks** [comment]
An Api for this would help. Looking forward to this
