### ISSUE TITLE
Update Oort's info

### ISSUE THREAD

**Issue by molecula451** [DefiLlama/chainlist#851]
We update Oort [info](https://github.com/ethereum-lists/chains/pull/3930) on ethereum-lists metadata, can you resync on your site?

**Comment by molecula451** [comment]
@realdealshaman

**Comment by realdealshaman** [comment]
Hey, @molecula451 is there any further updates needed? It looks like the changes have appeared on chianlist.org

**Comment by molecula451** [comment]
hey @realdealshaman the logo doesn't seem to be showing and it's showing at chainid.network perfectly

**Comment by 0xngmi** [comment]
We use logos from defillama so to display the logo the chain needs to be listed on defillama
