### ISSUE TITLE
Neon EVM Testnet not being deprecated

### ISSUE THREAD

**Issue by mnedelchev-vn** [DefiLlama/chainlist#856]
Hello, a week ago in **[this PR](https://github.com/ethereum-lists/chains/pull/3910)** I've deprecated Neon EVM Testnet chain and the PR got accepted and I believe since then the chainlist website has been updated, because I've other PRs accepted after this deprecating PR and these changes are already live. But I still see that chain at https://chainlist.org/?search=Neon+EVM&testnets=true. Can you please collaborate?

**Comment by mnedelchev-vn** [comment]
You can validate the deprecated status at [https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-245022940.json#L3](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-245022940.json#L3)

**Comment by 0xngmi** [comment]
fixed in #858
