### ISSUE TITLE
Defaulting to official RPC for chainId or listing official RPC first

### ISSUE THREAD

**Issue by wbnns** [DefiLlama/chainlist#883]
Hi there! HNY! I'm Will from the Base team. We're seeing increased reports from users in our community for some RPC providers for Base (chain: `8453`) who aren't estimating gas properly and causing people to encounter issues when trying to make transactions on the network.

I noticed our official RPC is a bit down on the list:
https://chainlist.org/chain/8453

I was going to open a PR to move mainnet.base.org up to the first position, however, I don't see it referenced anywhere in the code.

Any advice on how we could perhaps move it up to help alleviate the reported issue?

**Comment by realdealshaman** [comment]
Hey, thanks for reaching out, we addresses this already via our telegram group. Cheers

**Comment by realdealshaman** [comment]
I'll close this for now, please reach out if there's is any other concern. ty
