### ISSUE TITLE
Arthera Mainnet not synchronized from upstream

### ISSUE THREAD

**Issue by bertux** [DefiLlama/chainlist#894]
Hello, https://github.com/ethereum-lists/chains/pull/4083 has been merged 4 days ago and it's already displayed by other chainlist UI forks but not yet by yours. Should I make a PR as https://github.com/DefiLlama/chainlist/pull/863 or can you explain how to make it synchronized ?
Synchronization worked well for Athera Testnet without doing anything else then the merged PR as for Arthera Mainnet.

**Comment by realdealshaman** [comment]
added the rpcs, they'll be live in about one hour
