### ISSUE TITLE
Privacy Statements are meaningless when they claim 'no logs' or worse

### ISSUE THREAD

**Issue by sambacha** [DefiLlama/chainlist#945]
The problem with that no-logs claim, though, is that you can't prove a negative. Verifying that a service isn't logging user activity is impossible from the outside. 

Additionally, just because your service is routed through TOR does not mean it is without downsides: your exit traffic is still controlled by the exit TOR node. This means you can not only be censored, but also fed fake data masquerading as legit RPC traffic. You would never know.

All of these services use some sort of caching middleware, that in itself requires such logging and persisting of user connection information to be able to respond.

**Comment by Rjsoon38** [comment]
Thank you so much for the information. I really appreciate that guidance.

**Comment by Funinthesun210** [comment]
> The problem with that no-logs claim, though, is that you can't prove a negative. Verifying that a service isn't logging user activity is impossible from the outside.
> 
> Additionally, just because your service is routed through TOR does not mean it is without downsides: your exit traffic is still controlled by the exit TOR node. This means you can not only be censored, but also fed fake data masquerading as legit RPC traffic. You would never know.
> 
> All of these services use some sort of caching middleware, that in itself requires such logging and persisting of user connection information to be able to respond.

Thank you
