### ISSUE TITLE
Networks working locally but not on live site

### ISSUE THREAD

**Issue by blockjoe** [DefiLlama/chainlist#963]
Hey, we recently added a couple of endpoints via this PR: https://github.com/DefiLlama/chainlist/pull/956.

I noticed that on the main site that they're showing errors, but when I clone the repo and run it locally, we're not seeing these errors.

Any clue on what could be causing that?

Screenshots from the live site and then my local build respectively.

<img width="854" alt="Live site screenshot" src="https://github.com/DefiLlama/chainlist/assets/69400937/aee536f3-bd8c-4bb4-8d51-b376c4279e26">
<img width="1440" alt="localhost" src="https://github.com/DefiLlama/chainlist/assets/69400937/257204f1-d073-438c-ad31-6f9ddb16bbda">

**Comment by realdealshaman** [comment]
Hi @blockjoe , it's possible that the RPC is blocking our requests, affecting the retrieval of info such as the current block and response times on the live site, which might not occur in a local environment

**Comment by Itzyboo1** [comment]
Sorry I had to back to commits because J had accidentally skipped forward ahead of next 
step

**Comment by Amarylla923** [comment]
{[£∆, §,€∆, £€|f $§, π√π, @®™©°¥¢,  RC3°, ®©, ™^¢, B¢, D¢, 
Z$, 
¥€£@*, EROL, RL, RH, GRL, LRG, EAG, AMR, JHS, SAJ, JS, JSB, JBK, JK, Rosetree√, MELQZ, ALZQ, AQZ, QZS, ZZ², ZsQ³, S³, BMc2x9, CCC, RH, GER AlaneA, A&A, E&A, JA HSSTTRKNL, TRK, NAKTTSSJHS, Z3, Bzez, B10x10, B210, Amar, Mel, MilyWe, MilyZZ25, 22Gauge, Andrewssons, only daughter²DSZ, GEDZ, MJDZ, P³, pez, ezg, ghb, meb, ejb, mlb, akb, adb, akd, adrabd, ADRADB, AMRDADB, AKDBAMRD, RL, RHL, 
MZAMrAKBoara, RoRa,, RH, LGLL, EGLL, EAGLL, RHL², RJ, HP, BB, BBG, Mom, Me, Amar, AK, ADB, GMA, MG, GM, ION, NEO, NIO, }] 2-25-2024, +-12-+, I, I, eye, ay, ai,  }]
