### ISSUE TITLE
add logo for https://chainlist.org/?search=13381

### ISSUE THREAD

**Issue by Fluffynorth** [DefiLlama/chainlist#992]
logo_url=https://phoenixblockchain.org/wp-content/uploads/2021/11/phoenixweb.png

**Comment by realdealshaman** [comment]
Hey, @Fluffynorth we actually only add the logo to track which chains are already listed on Defillama

**Comment by Fluffynorth** [comment]
@realdealshaman you mean like this one https://chainlist.org/chain/13381 ? Phoenix os already tracked but it's showing greyed out eth logo instead of the Phoenix logo from the url I provided.

**Comment by Fluffynorth** [comment]
> @realdealshaman you mean like this one https://chainlist.org/chain/13381 ? Phoenix os already tracked but it's showing greyed out eth logo instead of the Phoenix logo from the url I provided.

Or you mean only chains added to here https://defillama.com/ ?
