### ISSUE TITLE
Score Issue (showing the (x) red symbol)

### ISSUE THREAD

**Issue by AmardeepSambaru** [DefiLlama/chainlist#994]
Hello Everyone
Good morning

I've set up the Etherlink public endpoint and uploaded it, and everything seems to be working fine. However, when checking the UI at "https://chainlist.org/?search=etherlink&testnets=true," I noticed that the score is showing a red symbol (X).

Could someone please explain the reason behind this and clarify what the score represents?

Thanks

![chainlist](https://github.com/DefiLlama/chainlist/assets/93637202/2ec4bc12-5adc-43f8-ad3b-ca0da51d21cd)

**Comment by realdealshaman** [comment]
Hi @AmardeepSambaru  , it's possible that the RPC is blocking our requests, affecting the retrieval of info such as the current block and response times on the live site, which might not occur in a local environment
